name: learn- github- actions

run-name: Alaettin is learning github actions
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-versin: '17'

      - name: java version
        run: java -version

      -name: java version print
       run: echo "Alaettin"