name: learn- github- actions

run-name: Alaettin is learning github actions
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'


      - run: java -version

      - run: echo "Alaettin"