
name: learn- github- acitons

on: [push]


jobs:

  checks- version:

    runs-on: ubuntu-latest

    steps: 

      - uses: actions/checkout@v4


      - uses: actions/setup-java@v4
        with:
          java-version: '11'

      - run: echo java --version
