name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    name: Java ${{matrix.java}} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: ${{matrix.java}}
      - name: Checkout another Repo
        run: |
          git clone https://github.com/krdyial/techproedsummer2020.git
            

      - name: Other step
        run:  |  
              cd techproedsummer2020
              pwd
              echo " Before"
              cd src/day01variablesdt
              javac Variables01.java
              echo "Middle"
              echo "After"
            
              

     

